export const quotes = [
	"1. A mis amigo/as les deseo un San Valentín lleno de amor, felicidad y aventuras!.",
	"2. A mis amigo/as les deseo un San Valentín lleno de recuerdos hermosos, risas y amor.",
	"3. A mis amigo/as les envío un mensaje lleno de amor y gratitud por ser una parte tan importante de mi vida.",
	"4. A mis amigo/as les envío un mensaje lleno de amor, agradecimiento y gratitud en el día de San Valentín.",
	"5. A ti, mi amigo/a incondicional, que siempre está ahí para apoyarme, ¡Feliz San Valentín!",
	"6. Aunque estamos lejos, mi amistad por ti siempre será fuerte. ¡Feliz San Valentín!",
	"7. Desde el fondo de mi corazón, quiero desearte un San Valentín lleno de amor y alegría. ¡Eres un(a) amigo/a maravilloso!",
	"8. El amor es divertido, pero tener un(a) amigo/as que te quiere es lo mejor del mundo. Feliz San Valentín.",
	"9. El amor verdadero es cuando puedes reír juntos, llorar juntos y ser tontos juntos. Eso es lo que tú y yo tenemos, amigo/as.",
	"10. En el día de San Valentín, les envío un abrazo virtual a mis amigo/as más queridos.",
	"11. Eres el regalo más preciado en mi vida y hoy te celebramos.",
	"12. Eres una luz de vida y el sol de los días grises.",
	"13. Eres la razón por la que la frase 'inseparables' tiene sentido. Feliz San Valentín, amigo/as mío/a.",
	"14. Eres mi alma gemela, mi confidente y mi amigo/as. Feliz San Valentín.",
	"15. Eres mi amigo/a de toda la vida y te agradezco por eso.",
	"16. Eres mi amigo/a fiel, mi compañero/a en todas las aventuras y mi confidente en los momentos difíciles.",
	"17. Eres mi amigo/a incondicional y estoy agradecido por eso. ¡Feliz San Valentín!",
	"18. Eres mi amigo/a incondicional, mi apoyo incansable y mi confidente.",
	"19. Eres mi amigo/a leal, y te agradezco por ser una presencia constante en mi vida.",
	"20. Eres mi confidente y mi mejor consejero, gracias por estar siempre a mi lado.",
	"21. Eres mi confidente, mi compañero/a de risas y mi amigo/a más fiel, ¡Feliz San Valentín!",
	"22. Eres mi confidente, mi cómplice y mi amigo/a más leal.",
	"23. Eres mi mejor amigo/a. Gracias por hacer mi vida más brillante y divertida todos los días.",
	"24. Eres un(a) amigo/a amable y un apoyo incansable. Feliz día del amor y la amistad.",
	"25. Eres un(a) amigo/a con un corazón generoso y un espíritu bondadoso. Feliz San Valentín.",
	"26. Eres un(a) amigo/a con un corazón gigante y te deseo un día lleno de amor y felicidad. Feliz San Valentín.",
	"27. Eres un(a) amigo/a con una sonrisa contagiosa y un espíritu joven. Feliz San Valentín.",
	"28. Eres un(a) amigo/a de verdad, y hoy quiero decirte lo mucho que te aprecio.",
	"29. Eres un(a) amigo/a divertido y un compañero/a de risas. Feliz San Valentín, amigo/a mío.",
	"30. Eres un(a) amigo/a en quien puedo confiar y apreciar, ¡Feliz San Valentín!",
	"31. Eres un(a) amigo/a en quien siempre puedo confiar y contar. Feliz día del amor y la amistad.",
	"32. Eres un(a) amigo/a en quien siempre puedo confiar y te quiero muchísimo, ¡Feliz San Valentín!",
	"33. Eres un(a) amigo/a especial que merece todo lo mejor en este día de amor y amistad. Feliz San Valentín.",
	"34. Eres un(a) amigo/a excepcional y estoy agradecido por todo lo que has hecho por mí. ¡Feliz San Valentín!",
	"35. Eres un(a) amigo/a incansable y siempre estás ahí para apoyarme. ¡Feliz San Valentín!",
	"36. Eres un(a) amigo/a inolvidable y una parte importante de mi vida. Feliz San Valentín.",
	"37. Eres un(a) amigo/a leal y sincero, y por eso te quiero con todo mi corazón, ¡feliz día de San Valentín!",
	"38. Eres un(a) amigo/a leal y una bendición en mi vida. Feliz día del amor y la amistad.",
	"39. Eres un(a) amigo/a maravilloso que hace mi vida más brillante, ¡Feliz San Valentín!",
	"40. Eres un(a) amigo/a maravilloso que siempre me hace reír, ¡Feliz San Valentín!",
	"41. Eres un(a) amigo/a maravilloso y me siento afortunado de tenerte a mi lado. ¡Feliz San Valentín!",
	"42. Eres un(a) amigo/a maravilloso, y estoy agradecido por tenerte en mi vida, ¡feliz día de San Valentín!",
	"43. Eres un(a) amigo/a que ilumina mi camino en las buenas y en las malas, ¡Feliz San Valentín!",
	"44. Eres un(a) amigo/a único y especial, y te quiero con todo mi corazón, ¡feliz día de San Valentín!",
	"45. Eres un(a) amigo/a único y te aprecio muchísimo. ¡Feliz San Valentín!",
	"46. Eres un(a) amigo/a único y te envío un abrazo lleno de amor en este día de San Valentín.",
	"47. Eres un(a) amigo/a único y una parte importante de mi vida. Feliz San Valentín, amigo/a mío.",
	"48. Eres un(a) amigo/a único, y te agradezco por hacer mi vida más brillante y alegre.",
	"49. Eres un(a) amigo/a valiente y un compañero/a confiable. Feliz San Valentín, amigo/a mío.",
	"50. Eres un(a) amigo/a valioso en mi vida, y estoy agradecido por tenerte siempre a mi lado, ¡Feliz San Valentín!",
	"51. Eres un(a) amigo/a verdadero en todo momento, hoy y siempre, Feliz San Valentín.",
	"52. Eres un(a) amigo/a verdadero y por eso te quiero con todo mi corazón, ¡feliz día de San Valentín!",
	"53. Eres un(a) amigo/a verdadero y te deseo lo mejor en este día de San Valentín y siempre.",
	"54. Eres un(a) amigo/a verdadero, siempre presente en los buenos y malos momentos.",
	"55. Eres un verdadero amigo/a, alguien en quien siempre puedo confiar. ¡Feliz San Valentín!",
	"56. Eres una bendición en mi vida y estoy agradecido por tenerte como amigo/a. Feliz San Valentín.",
	"57. Eres una bendición en mi vida y me siento afortunado de tenerte como amigo/a. ¡Feliz San Valentín!",
	"58. Eres una bendición en mi vida y quiero que sepas que te aprecio muchísimo. ¡Feliz San Valentín!",
	"59. Eres una bendición en mi vida, gracias por ser mi amigo/a incondicional, ¡feliz día de San Valentín!",
	"60. Eres una luz brillante en mi vida y te quiero muchísimo, ¡Feliz San Valentín!",
	"61. Eres una parte importante de mi vida y estoy agradecido por tenerte en ella.",
	"62. Eres una parte integral de mi vida y me alegro de tenerte como amigo/a. ¡Feliz San Valentín!",
	"63. Espero que hoy sea un día lleno de amor, risas y alegría para ti y los que te rodean. ¡Feliz San Valentín!",
	"64. Este San Valentín, les envío mi corazón y mi amor a mis amigo/as más queridos.",
	"65. Este San Valentín, les envío un abrazo virtual y mucho amor a mis amigo/as lejanos.",
	"66. Este San Valentín, quiero agradecer a mis amigo/as por ser una parte importante de mi vida y llenarla de alegría.",
	"67. Este San Valentín, quiero celebrar el amor verdadero que tengo por mis amigo/as.",
	"68. Este San Valentín, quiero decirle a mis amigo/as lo mucho que significan para mí y cuánto los quiero.",
	"69. Este San Valentín, quiero decirles a mis amigo/as lo mucho que los aprecio y cuánto los quiero.",
	"70. Estoy agradecido por tenerte como amigo/a y por todos los buenos momentos que hemos compartido juntos. Feliz San Valentín.",
	"71. Feliz San Valentín a mi amigo/as, mi confidente, mi cómplice y mi compañero/a/a en todas las travesuras.",
	"72. Gracias por estar ahí y por ser un(a) amigo/a incansable. Feliz San Valentín, amigo/a mío.",
	"73. Gracias por ser mi amigo/a incondicional, mi confidente y mi compañero/a de risas, ¡feliz día de San Valentín!",
	"74. Gracias por ser mi amigo/a y mi compañero/a en todas las aventuras de la vida.",
	"75. Gracias por ser mi amigo/a y por siempre estar ahí para mí. ¡Feliz San Valentín!",
	"76. Gracias por ser mi amigo/a, mi compañero/a de aventuras y mi confidente, ¡feliz día de San Valentín!",
	"77. Gracias por ser mi confidente, mi compañero/a de aventuras y mi amigo/a. ¡Feliz San Valentín!",
	"78. Gracias por ser un(a) amigo/a tan incondicional y estar ahí en todo momento. Feliz San Valentín.",
	"79. Gracias por ser un compañero/a de aventuras y por hacer mi vida más divertida. Feliz San Valentín.",
	"80. Hoy celebramos el amor, pero contigo lo hacemos todos los días.",
	"81. Hoy es un día especial para celebrar el amor, pero para mí, cada día es especial porque tengo amigo/as tan maravillosos.",
	"82. Hoy es un día para celebrar el amor, incluyendo la amistad que compartimos. ¡Feliz San Valentín!",
	"83. Hoy es un día para decirle a mis amigo/as cuánto los valoro y cuánto los quiero.",
	"84. Hoy es un día para reflexionar sobre el valor de la amistad, y quiero decirte que la tuya es invaluable para mí. ¡Feliz San Valentín!",
	"85. Mi amigo/as es la mejor cosa que me ha pasado en la vida, después del chocolate y los abrazos.",
	"86. Mis amigo/as son la luz de mi vida, les deseo un San Valentín lleno de amor y risas.",
	"87. Mis amigo/as son mi familia elegida, les deseo un feliz día de San Valentín lleno de amor.",
	"88. Mis amigo/as son mis confidentes, mis compañero/as de aventura y mi familia elegida. Les deseo un Feliz San Valentín.",
	"89. Mis amigo/as son un regalo de la vida, les deseo un San Valentín lleno de amor y alegría.",
	"90. No hay nada más bonito que el amor, a menos que sea amor de mi amigo/as hacia mí.",
	"91. No hay nada más bonito que el amor, a menos que sea amor de mi amigo/as hacia mí.",
	"92. No hay nadie más a quien le guste hacer el amor que a mi amigo/as. Eres un adicto/a al amor!",
	"93. No importa cuánto tiempo pase, siempre estaré aquí para apoyarte y amarte, amigo/as mío/a.",
	"94. No puedo imaginar mi vida sin ti, gracias por ser parte de ella.",
	"95. Nunca voy a olvidar los buenos momentos que hemos compartido juntos. Eres un(a) amigo/a para siempre. Feliz San Valentín.",
	"96. Que este día especial esté lleno de amor, risas y momentos inolvidables junto a ti, amigo/a mío.",
	"97. Que este San Valentín traiga mucho amor, risas y recuerdos hermosos con mis amigo/as.",
	"98. Quiero desearte un amoroso San Valentín, lleno de risas y alegría, junto a tus seres queridos.",
	"99. Quiero que mis amigo/as sepan que están en mi corazón todos los días, especialmente en el día de San Valentín.",
	"100. Quiero que mis amigo/as sepan que son valiosos, queridos y amados en el día de San Valentín y siempre.",
	"101. Te agradezco por ser mi amigo/a, mi confidente y mi compañero/a en la vida.",
	"102. Te deseo un día lleno de amor, risas y mucha felicidad.",
	"103. Te deseo un hermoso San Valentín, lleno de risas, amor y alegría. ¡Eres un(a) amigo/a maravilloso!",
	"104. Te quiero mucho amigo/a, y estoy agradecido por todo lo que has hecho por mí.",
	"105. Te quiero mucho amigo/a, y estoy agradecido por tus consejos y tu apoyo incondicional.",
	"106. Te quiero mucho amigo/a, y hoy quiero decirte lo mucho que te aprecio y lo mucho que te quiero.",
	"107. Un verdadero amigo/a es alguien que cree en ti aunque tú hayas dejado de creer en ti mismo.",
	"108. La amistad es el ingrediente más importante en la receta de la vida.",
	"109. un(a) amigo/a es alguien que te conoce tal como eres, comprende dónde has estado, acepta quién te has convertido y aún así te permite crecer.",
	"110. un(a) amigo/a es alguien que te da total libertad para ser tú mismo.",
	"111. un(a) amigo/a es alguien que te da la libertad de ser tú mismo y aún así te ama por quien eres.",
	"112. La amistad es el arte de estar juntos cuando todo lo demás se desmorona.",
	"113. un(a) amigo/a es alguien que te conoce tan bien que te ayuda a encontrar tus propias respuestas.",
	"114. La verdadera amistad no se trata de ser inseparables, sino de estar separados y saber que nada cambiará.",
	"115. un(a) amigo/a es alguien que te da la mano y toca tu corazón.",
	"116. La amistad no se trata de quién vino primero o quién duró más, sino de quién nunca se fue y siempre estuvo ahí.",
];
