export const quotes = [
	"1. A mis amig@s les deseo un San Valentín lleno de amor, felicidad y aventuras juntos.",
	"2. A mis amig@s les deseo un San Valentín lleno de recuerdos hermosos, risas y amor.",
	"3. A mis amig@s les envío un mensaje lleno de amor y gratitud por ser una parte tan importante de mi vida.",
	"4. A mis amig@s les envío un mensaje lleno de amor, agradecimiento y gratitud en el día de San Valentín.",
	"5. A ti, mi amig@ incondicional, que siempre está ahí para apoyarme, ¡Feliz San Valentín!",
	"6. Aunque estamos lejos, mi amistad por ti siempre será fuerte. ¡Feliz San Valentín!",
	"7. Desde el fondo de mi corazón, quiero desearte un San Valentín lleno de amor y alegría. ¡Eres un amig@ maravilloso!",
	"8. El amor es divertido, pero tener un amig@s que te quiere es lo mejor del mundo. Feliz San Valentín.",
	"9. El amor verdadero es cuando puedes reír juntos, llorar juntos y ser tontos juntos. Eso es lo que tú y yo tenemos, amig@s.",
	"10. En el día de San Valentín, les envío un abrazo virtual a mis amig@s más queridos.",
	"11. Eres el regalo más preciado en mi vida y hoy te celebramos.",
	"12. Eres la luz de mi vida y el sol en mis días grises.",
	"13. Eres la razón por la que la frase 'inseparables' tiene sentido. Feliz San Valentín, amig@s mío/a.",
	"14. Eres mi alma gemela, mi confidente y mi amig@s. Feliz San Valentín.",
	"15. Eres mi amig@ de toda la vida y te agradezco por eso.",
	"16. Eres mi amig@ fiel, mi compañer@ en todas las aventuras y mi confidente en los momentos difíciles.",
	"17. Eres mi amig@ incondicional y estoy agradecido por eso. ¡Feliz San Valentín!",
	"18. Eres mi amig@ incondicional, mi apoyo incansable y mi confidente.",
	"19. Eres mi amig@ leal, y te agradezco por ser una presencia constante en mi vida.",
	"20. Eres mi confidente y mi mejor consejero, gracias por estar siempre a mi lado.",
	"21. Eres mi confidente, mi compañer@ de risas y mi amig@ más fiel, ¡Feliz San Valentín!",
	"22. Eres mi confidente, mi cómplice y mi amig@ más leal.",
	"23. Eres mi mejor amig@s. Gracias por hacer mi vida más brillante y divertida todos los días.",
	"24. Eres un amig@ amable y un apoyo incansable. Feliz día del amor y la amistad.",
	"25. Eres un amig@ con un corazón generoso y un espíritu bondadoso. Feliz San Valentín.",
	"26. Eres un amig@ con un corazón gigante y te deseo un día lleno de amor y felicidad. Feliz San Valentín.",
	"27. Eres un amig@ con una sonrisa contagiosa y un espíritu joven. Feliz San Valentín.",
	"28. Eres un amig@ de verdad, y hoy quiero decirte lo mucho que te aprecio.",
	"29. Eres un amig@ divertido y un compañer@ de risas. Feliz San Valentín, amig@ mío.",
	"30. Eres un amig@ en quien puedo confiar y apreciar, ¡Feliz San Valentín!",
	"31. Eres un amig@ en quien siempre puedo confiar y contar. Feliz día del amor y la amistad.",
	"32. Eres un amig@ en quien siempre puedo confiar y te quiero muchísimo, ¡Feliz San Valentín!",
	"33. Eres un amig@ especial que merece todo lo mejor en este día de amor y amistad. Feliz San Valentín.",
	"34. Eres un amig@ excepcional y estoy agradecido por todo lo que has hecho por mí. ¡Feliz San Valentín!",
	"35. Eres un amig@ incansable y siempre estás ahí para apoyarme. ¡Feliz San Valentín!",
	"36. Eres un amig@ inolvidable y una parte importante de mi vida. Feliz San Valentín.",
	"37. Eres un amig@ leal y sincero, y por eso te quiero con todo mi corazón, ¡feliz día de San Valentín!",
	"38. Eres un amig@ leal y una bendición en mi vida. Feliz día del amor y la amistad.",
	"39. Eres un amig@ maravilloso que hace mi vida más brillante, ¡Feliz San Valentín!",
	"40. Eres un amig@ maravilloso que siempre me hace reír, ¡Feliz San Valentín!",
	"41. Eres un amig@ maravilloso y me siento afortunado de tenerte a mi lado. ¡Feliz San Valentín!",
	"42. Eres un amig@ maravilloso, y estoy agradecido por tenerte en mi vida, ¡feliz día de San Valentín!",
	"43. Eres un amig@ que ilumina mi camino en las buenas y en las malas, ¡Feliz San Valentín!",
	"44. Eres un amig@ único y especial, y te quiero con todo mi corazón, ¡feliz día de San Valentín!",
	"45. Eres un amig@ único y te aprecio muchísimo. ¡Feliz San Valentín!",
	"46. Eres un amig@ único y te envío un abrazo lleno de amor en este día de San Valentín.",
	"47. Eres un amig@ único y una parte importante de mi vida. Feliz San Valentín, amig@ mío.",
	"48. Eres un amig@ único, y te agradezco por hacer mi vida más brillante y alegre.",
	"49. Eres un amig@ valiente y un compañer@ confiable. Feliz San Valentín, amig@ mío.",
	"50. Eres un amig@ valioso en mi vida, y estoy agradecido por tenerte siempre a mi lado, ¡Feliz San Valentín!",
	"51. Eres un amig@ verdadero en todo momento, hoy y siempre, Feliz San Valentín.",
	"52. Eres un amig@ verdadero y por eso te quiero con todo mi corazón, ¡feliz día de San Valentín!",
	"53. Eres un amig@ verdadero y te deseo lo mejor en este día de San Valentín y siempre.",
	"54. Eres un amig@ verdadero, siempre presente en los buenos y malos momentos.",
	"55. Eres un verdadero amig@, alguien en quien siempre puedo confiar. ¡Feliz San Valentín!",
	"56. Eres una bendición en mi vida y estoy agradecido por tenerte como amig@. Feliz San Valentín.",
	"57. Eres una bendición en mi vida y me siento afortunado de tenerte como amig@. ¡Feliz San Valentín!",
	"58. Eres una bendición en mi vida y quiero que sepas que te aprecio muchísimo. ¡Feliz San Valentín!",
	"59. Eres una bendición en mi vida, gracias por ser mi amig@ incondicional, ¡feliz día de San Valentín!",
	"60. Eres una luz brillante en mi vida y te quiero muchísimo, ¡Feliz San Valentín!",
	"61. Eres una parte importante de mi vida y estoy agradecido por tenerte en ella.",
	"62. Eres una parte integral de mi vida y me alegro de tenerte como amig@. ¡Feliz San Valentín!",
	"63. Espero que hoy sea un día lleno de amor, risas y alegría para ti y los que te rodean. ¡Feliz San Valentín!",
	"64. Este San Valentín, les envío mi corazón y mi amor a mis amig@s más queridos.",
	"65. Este San Valentín, les envío un abrazo virtual y mucho amor a mis amig@s lejanos.",
	"66. Este San Valentín, quiero agradecer a mis amig@s por ser una parte importante de mi vida y llenarla de alegría.",
	"67. Este San Valentín, quiero celebrar el amor verdadero que tengo por mis amig@s.",
	"68. Este San Valentín, quiero decirle a mis amig@s lo mucho que significan para mí y cuánto los quiero.",
	"69. Este San Valentín, quiero decirles a mis amig@s lo mucho que los aprecio y cuánto los quiero.",
	"70. Estoy agradecido por tenerte como amig@ y por todos los buenos momentos que hemos compartido juntos. Feliz San Valentín.",
	"71. Feliz San Valentín a mi amig@s, mi confidente, mi cómplice y mi compañer@/a en todas las travesuras.",
	"72. Gracias por estar ahí y por ser un amig@ incansable. Feliz San Valentín, amig@ mío.",
	"73. Gracias por ser mi amig@ incondicional, mi confidente y mi compañer@ de risas, ¡feliz día de San Valentín!",
	"74. Gracias por ser mi amig@ y mi compañer@ en todas las aventuras de la vida.",
	"75. Gracias por ser mi amig@ y por siempre estar ahí para mí. ¡Feliz San Valentín!",
	"76. Gracias por ser mi amig@, mi compañer@ de aventuras y mi confidente, ¡feliz día de San Valentín!",
	"77. Gracias por ser mi confidente, mi compañer@ de aventuras y mi amig@. ¡Feliz San Valentín!",
	"78. Gracias por ser un amig@ tan incondicional y estar ahí en todo momento. Feliz San Valentín.",
	"79. Gracias por ser un compañer@ de aventuras y por hacer mi vida más divertida. Feliz San Valentín.",
	"80. Hoy celebramos el amor, pero contigo lo hacemos todos los días.",
	"81. Hoy es un día especial para celebrar el amor, pero para mí, cada día es especial porque tengo amig@s tan maravillosos.",
	"82. Hoy es un día para celebrar el amor, incluyendo la amistad que compartimos. ¡Feliz San Valentín!",
	"83. Hoy es un día para decirle a mis amig@s cuánto los valoro y cuánto los quiero.",
	"84. Hoy es un día para reflexionar sobre el valor de la amistad, y quiero decirte que la tuya es invaluable para mí. ¡Feliz San Valentín!",
	"85. Mi amig@s es la mejor cosa que me ha pasado en la vida, después del chocolate y los abrazos.",
	"86. Mis amig@s son la luz de mi vida, les deseo un San Valentín lleno de amor y risas.",
	"87. Mis amig@s son mi familia elegida, les deseo un feliz día de }" +
	"San Valentín lleno de amor.",
	"88. Mis amig@s son mis confidentes, mis compañer@s de aventura y mi familia elegida. Les deseo un Feliz San Valentín.",
	"89. Mis amig@s son un regalo de la vida, les deseo un San Valentín lleno de amor y alegría.",
	"90. No hay nada más bonito que el amor, a menos que sea amor de mi amig@s hacia mí.",
	"91. No hay nada más bonito que el amor, a menos que sea amor de mi amig@s hacia mí.",
	"92. No hay nadie más a quien le guste hacer el amor que a mi amig@s. Eres un adicto/a al amor!",
	"93. No importa cuánto tiempo pase, siempre estaré aquí para apoyarte y amarte, amig@s mío/a.",
	"94. No puedo imaginar mi vida sin ti, gracias por ser parte de ella.",
	"95. Nunca voy a olvidar los buenos momentos que hemos compartido juntos. Eres un amig@ para siempre. Feliz San Valentín.",
	"96. Que este día especial esté lleno de amor, risas y momentos inolvidables junto a ti, amig@ mío.",
	"97. Que este San Valentín traiga mucho amor, risas y recuerdos hermosos con mis amig@s.",
	"98. Quiero desearte un amoroso San Valentín, lleno de risas y alegría, junto a tus seres queridos.",
	"99. Quiero que mis amig@s sepan que están en mi corazón todos los días, especialmente en el día de San Valentín.",
	"100. Quiero que mis amig@s sepan que son valiosos, queridos y amados en el día de San Valentín y siempre.",
	"101. Te agradezco por ser mi amig@, mi confidente y mi compañer@ en la vida.",
	"102. Te deseo un día lleno de amor, risas y mucha felicidad.",
	"103. Te deseo un hermoso San Valentín, lleno de risas, amor y alegría. ¡Eres un amig@ maravilloso!",
	"104. Te quiero mucho amig@, y estoy agradecido por todo lo que has hecho por mí.",
	"105. Te quiero mucho amig@, y estoy agradecido por tus consejos y tu apoyo incondicional.",
	"106. Te quiero mucho amig@, y hoy quiero decirte lo mucho que te aprecio y lo mucho que te quiero.",
];
